### ISSUE TITLE
Causes crashes with llitematica

### ISSUE THREAD

**Issue by Telcote** [emilyalexandra/chime#6]
Thread: Render thread
Stacktrace:
	at net.minecraft.class_799.handler$zko000$matches(class_799.java:528)
	at net.minecraft.class_799.method_3473(class_799.java:41)
	at net.minecraft.class_806.method_3495(class_806.java:50)
	at net.minecraft.class_918.method_4019(class_918.java:249)
	at net.minecraft.class_918.method_23177(class_918.java:262)
	at net.minecraft.class_918.method_23178(class_918.java:254)
	at net.minecraft.class_915.method_3994(class_915.java:91)
	at net.minecraft.class_915.method_3936(class_915.java:24)

-- Entity being rendered --
Details:
	Entity Type: minecraft:item_frame (net.minecraft.class_1533)
	Entity ID: 11
	Entity Name: Item Frame
	Entity's Exact location: 374.97, 67.50, 54.50
	Entity's Block location: World: (374,67,54), Chunk: (at 6,4,6 in 23,3; contains blocks 368,0,48 to 383,255,63), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Entity's Momentum: 0.00, 0.00, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null

-- Renderer details --
Details:
	Assigned renderer: net.minecraft.class_915@5a58fe0c
	Location: 29.61,1.88,20.04 - World: (29,1,20), Chunk: (at 13,0,4 in 1,1; contains blocks 16,0,16 to 31,255,31), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Rotation: 90.0
	Delta: 0.2200036
Stacktrace:
	at net.minecraft.class_898.method_3954(class_898.java:261)
	at fi.dy.masa.litematica.render.schematic.WorldRendererSchematic.renderEntities(WorldRendererSchematic.java:660)
	at fi.dy.masa.litematica.render.LitematicaRenderer.piecewiseRenderEntities(LitematicaRenderer.java:480)
	at net.minecraft.class_761.handler$bbm000$onPostRenderEntities(class_761.java:9652)
	at net.minecraft.class_761.method_22710(class_761.java:1229)
	at net.minecraft.class_757.method_3188(class_757.java:727)

-- Affected level --
Details:
	All players: 1 total; [class_746['Br34th3n'/3286, l='ClientLevel', x=345.36, y=64.00, z=34.46]]
	Chunk stats: SodiumChunkCache: 431
	Level dimension: minecraft:overworld
	Level spawn location: World: (288,64,8), Chunk: (at 0,4,8 in 18,0; contains blocks 288,0,0 to 303,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 57394 game time, 5203115 day time
	Server brand: Paper
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:449)
	at net.minecraft.class_310.method_1587(class_310.java:2239)
	at net.minecraft.class_310.method_1514(class_310.java:699)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:146)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)

**Comment by LucilleTea** [comment]
Is your Chime up to date? A bug like this has already been fixed.

**Comment by emilyalexandra** [comment]
Please upload the entire crashlog so I can see the mods you are using and what version they're on, as well as portions of the crash log you may have cut out

**Comment by Telcote** [comment]
Update fixed it, everything works now :P
